// Generates known-answer vectors for src/LightningRSA/LightningRSA.sol and
// src/LightningRSA/LightningRSAAccount.yul: a real RSA-2048 keypair
// (generated by Node's own crypto module, not this repo's math), signed
// with Node's real RSASSA-PKCS1-v1_5/SHA-256 implementation, cross-checked
// two ways before being trusted — Node's own `crypto.verify` (does a real
// library accept its own signature?) and this repo's from-scratch
// `verifyPkcs1v15` (does our reimplementation agree with a real library?).
// Same "derive and verify before trusting the Solidity/Yul" discipline as
// gen-vectors.ts (BIP-340) and gen-toy-curve-vectors.ts.
//
// Written to test/vectors/lightning-rsa-vectors.json, read back by
// test/js/LightningRSA.test.ts and transcribed into
// test/solidity/LightningRSA/LightningRSA.t.sol.
//
// IMPORTANT: this keypair is a TEST FIXTURE ONLY, generated fresh each run
// and fine to commit — its entire purpose is checking the verify math is
// correct, not staying secret. A real deployed LightningRSA account must
// generate its own keypair locally, with the private key never written to
// any committed file.
//
// Run: pnpm tsx scripts/gen-lightning-rsa-vectors.ts

import {writeFileSync} from 'node:fs';
import {
	generateRsaKeypair,
	nodeSignMsgHash,
	nodeVerifyMsgHash,
	verifyPkcs1v15,
	bigIntToHex,
	bytesToHex,
} from '../test/js/utils/pkcs1.js';

const MODULUS_LENGTH = 2048; // -> 256 bytes -> 8 EVM words
// e=3, not the usual 65537: MODEXP's EIP-2565 gas cost scales with the
// *exponent's* bit-length (iteration_count), not the modulus's — at
// e=65537 (17 bits) a single RSA-2048 verify costs roughly 200k gas by
// that formula, comfortably over EIP-8141's MAX_VERIFY_GAS=100_000 public-
// mempool ceiling; at e=3 (2 bits) it drops to roughly 13k. See
// LightningRSAAccount.yul's header for the gas budget this was checked
// against, and why verifying via full EM reconstruction (not parsing
// padding out of the recovered value) closes the historical low-exponent
// forgery class this choice would otherwise reopen.
const PUBLIC_EXPONENT = 3;
const kp = generateRsaKeypair(MODULUS_LENGTH, PUBLIC_EXPONENT);
console.log(`Generated a fresh RSA-${MODULUS_LENGTH} keypair (n = ${kp.modulusBytes} bytes, e = ${kp.e}).`);

const MESSAGE_HASHES = [Buffer.alloc(32, 0x11), Buffer.from('deadbeef'.repeat(8), 'hex'), Buffer.alloc(32, 0)];

const signVectors = MESSAGE_HASHES.map((msgHash, i) => {
	const signature = nodeSignMsgHash(msgHash, kp.privateKeyPem);
	if (signature.length !== kp.modulusBytes) {
		throw new Error(`vector ${i}: signature length ${signature.length} != modulus length ${kp.modulusBytes}`);
	}

	// 1) A real library accepts its own signature.
	if (!nodeVerifyMsgHash(msgHash, signature, kp.publicKeyPem)) {
		console.error(`vector ${i}: Node's own crypto.verify rejected Node's own signature — should be impossible.`);
		process.exit(1);
	}

	// 2) Our from-scratch reimplementation agrees with the real library.
	const signatureInt = BigInt('0x' + signature.toString('hex'));
	if (!verifyPkcs1v15(kp.n, kp.e, signatureInt, msgHash, kp.modulusBytes)) {
		console.error(`vector ${i}: our from-scratch verifyPkcs1v15 rejected a real, Node-verified signature — the reimplementation is wrong.`);
		process.exit(1);
	}

	console.log(`vector ${i}: signed and cross-verified (Node + from-scratch).`);
	return {msgHash: bytesToHex(msgHash), signature: bytesToHex(signature)};
});

// A deliberately-invalid vector: flip the low bit of a real signature.
// Must be rejected by both the real library and our reimplementation.
const tamperedSignature = Buffer.from(nodeSignMsgHash(MESSAGE_HASHES[0], kp.privateKeyPem));
tamperedSignature[tamperedSignature.length - 1] ^= 0x01;
const tamperedInt = BigInt('0x' + tamperedSignature.toString('hex'));
if (nodeVerifyMsgHash(MESSAGE_HASHES[0], tamperedSignature, kp.publicKeyPem)) {
	console.error('tampered vector: Node accepted a bit-flipped signature — tampering did not take effect.');
	process.exit(1);
}
if (verifyPkcs1v15(kp.n, kp.e, tamperedInt, MESSAGE_HASHES[0], kp.modulusBytes)) {
	console.error('tampered vector: our from-scratch verify accepted a bit-flipped signature.');
	process.exit(1);
}
console.log('tampered vector: rejected by both Node and our from-scratch verify, as expected.');

const output = {
	modulusBits: MODULUS_LENGTH,
	modulusBytes: kp.modulusBytes,
	n: bigIntToHex(kp.n, kp.modulusBytes),
	e: bigIntToHex(kp.e, Math.ceil(kp.e.toString(16).length / 2)),
	signVectors,
	invalidVector: {msgHash: bytesToHex(MESSAGE_HASHES[0]), signature: bytesToHex(tamperedSignature)},
};

console.log('\nWriting test/vectors/lightning-rsa-vectors.json ...');
writeFileSync(
	new URL('../test/vectors/lightning-rsa-vectors.json', import.meta.url),
	JSON.stringify(output, null, 2) + '\n',
);
console.log('Done.');
