// Cross-checks BIP340.sol's ecrecover-trick reduction against `nostr-tools`
// — a real Nostr signing library, independent of both this repo's Solidity
// and its own scripts/gen-vectors.ts — per nostr-frame-schnorr-design.md
// §7 item 3: "generate a signature with a real Nostr signing library ...
// and verify it passes our contract — this is the test that actually
// proves the 'same key, two protocols' claim, not just internal
// self-consistency."
//
// This runs the reduction in plain JS (test/js/utils/bip340.ts), not
// against the deployed Solidity — see that file's header for why a
// pure-library, no-EVM-context check is the right shape here. The
// on-chain equivalent (same math, `ecrecover`-based) lives in
// test/solidity/BIP340/BIP340.t.sol.
import {expect} from 'earl';
import {describe, it} from 'node:test';
import {readFileSync} from 'node:fs';
import {
	finalizeEvent,
	generateSecretKey,
	verifyEvent,
	type EventTemplate,
} from 'nostr-tools/pure';
import {liftX, pointAddress, verifyEcrecoverTrick} from './utils/bip340.js';

function bip340SignatureFromEvent(event: {
	pubkey: string;
	sig: string;
	id: string;
}) {
	return {
		px: '0x' + event.pubkey,
		rx: '0x' + event.sig.slice(0, 64),
		s: '0x' + event.sig.slice(64, 128),
		message: '0x' + event.id,
	};
}

describe('BIP340 vs. nostr-tools', function () {
	it('accepts a freshly nostr-tools-signed event via the ecrecover-trick reduction', function () {
		const secretKey = generateSecretKey();
		const template: EventTemplate = {
			kind: 1,
			created_at: Math.floor(Date.now() / 1000),
			tags: [],
			content: 'hello from a real nostr-tools event',
		};

		const event = finalizeEvent(template, secretKey);

		// Pin the reference before cross-checking our own reduction against it:
		// nostr-tools must accept its own signature.
		expect(verifyEvent(event)).toEqual(true);

		const sig = bip340SignatureFromEvent(event);
		const pAddress = pointAddress(liftX(Buffer.from(event.pubkey, 'hex')));

		const {recoveredEqualsP, recoveredAddress} = verifyEcrecoverTrick(sig);

		expect(recoveredEqualsP).toEqual(true);
		// This is the exact comparison BIP340.sol's `verify` performs on-chain
		// (it only ever gets to compare 20-byte addresses, not raw points).
		expect(recoveredAddress.toLowerCase()).toEqual(pAddress.toLowerCase());
	});

	it('rejects when the signature is tampered with after signing', function () {
		const secretKey = generateSecretKey();
		const event = finalizeEvent(
			{
				kind: 1,
				created_at: Math.floor(Date.now() / 1000),
				tags: [],
				content: 'this event will be tampered with',
			},
			secretKey,
		);

		const sig = bip340SignatureFromEvent(event);
		// Flip a low bit of s — same tamper BIP340.t.sol's
		// test_flippedBitInS_rejected exercises on-chain.
		sig.s = '0x' + (BigInt(sig.s) ^ 1n).toString(16).padStart(64, '0');

		const {recoveredEqualsP} = verifyEcrecoverTrick(sig);
		expect(recoveredEqualsP).toEqual(false);
	});

	it('reproduces the pinned real-event vector hardcoded in BIP340.t.sol', function () {
		// Generated by scripts/gen-nostr-tools-vector.ts. Kept in sync with
		// test/solidity/BIP340/BIP340.t.sol's `v3` so the same numbers are
		// proven equivalent on both the JS reference and the Solidity
		// implementation.
		const vectorsPath = new URL(
			'../vectors/nostr-test-vectors.json',
			import.meta.url,
		);
		const vectors = JSON.parse(readFileSync(vectorsPath, 'utf8')) as Array<{
			description: string;
			px: string;
			pAddress: string;
			message: string;
			rx: string;
			s: string;
		}>;
		const vector = vectors.find(
			(v) => v.description === 'nostr-tools-real-event',
		);
		if (!vector)
			throw new Error(
				'missing "nostr-tools-real-event" vector — run scripts/gen-nostr-tools-vector.ts',
			);

		const {recoveredEqualsP, recoveredAddress} = verifyEcrecoverTrick(vector);

		expect(recoveredEqualsP).toEqual(true);
		expect(recoveredAddress.toLowerCase()).toEqual(
			vector.pAddress.toLowerCase(),
		);
	});
});
