// Tests src/grimoire/post-quantum/Falcon/falcon.ts (a from-scratch,
// verify-only Falcon-512 implementation) against the pinned known-answer
// vectors in test/vectors/falcon-vectors.json (generated by
// scripts/gen-falcon-vectors.ts, checked there against real signatures
// from @noble/post-quantum), and with a fresh, live signature verified
// directly against noble in this test — the actual "this accepts real
// Falcon-512 signatures, not just internally consistent" proof.
import {expect} from 'earl';
import {describe, it} from 'node:test';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {verify} from '../../src/grimoire/post-quantum/Falcon/falcon.js';
import {falcon512padded} from '@noble/post-quantum/falcon.js';

function fromHex(h: string): Uint8Array {
	return new Uint8Array(Buffer.from(h.slice(2), 'hex'));
}

interface Vectors {
	scheme: string;
	publicKey: string;
	signVectors: {message: string; signature: string}[];
	invalidVector: {message: string; signature: string};
}

const vectorsJson: Vectors = JSON.parse(
	readFileSync(fileURLToPath(new URL('../vectors/falcon-vectors.json', import.meta.url)), 'utf8'),
);

describe('Falcon (grimoire, post-quantum) — pinned known-answer vectors', function () {
	const publicKey = fromHex(vectorsJson.publicKey);

	for (const [i, v] of vectorsJson.signVectors.entries()) {
		it(`accepts real Falcon-512 sign vector ${i} ("${v.message}")`, function () {
			const message = new TextEncoder().encode(v.message);
			const signature = fromHex(v.signature);
			expect(verify(message, signature, publicKey)).toEqual(true);
		});
	}

	it('rejects the pinned tampered vector', function () {
		const message = new TextEncoder().encode(vectorsJson.invalidVector.message);
		const signature = fromHex(vectorsJson.invalidVector.signature);
		expect(verify(message, signature, publicKey)).toEqual(false);
	});

	it('rejects a signature crossed with the wrong message', function () {
		const wrongMessage = new TextEncoder().encode('a message that was never signed');
		const signature = fromHex(vectorsJson.signVectors[0]!.signature);
		expect(verify(wrongMessage, signature, publicKey)).toEqual(false);
	});
});

describe('Falcon — live verification against @noble/post-quantum directly', function () {
	it('accepts a fresh, real Falcon-512 signature at a fresh keypair', function () {
		const {secretKey, publicKey} = falcon512padded.keygen();
		const message = new Uint8Array([9, 8, 7, 6, 5, 4, 3, 2, 1]);
		const signature = falcon512padded.sign(message, secretKey);

		expect(falcon512padded.verify(signature, message, publicKey)).toEqual(true); // sanity: noble accepts its own signature
		expect(verify(message, signature, publicKey)).toEqual(true);
	});

	it('rejects a freshly tampered real signature', function () {
		const {secretKey, publicKey} = falcon512padded.keygen();
		const message = new Uint8Array([1, 1, 2, 3, 5, 8, 13]);
		const signature = falcon512padded.sign(message, secretKey);

		const tampered = Uint8Array.from(signature);
		tampered[100]! ^= 1;

		expect(falcon512padded.verify(tampered, message, publicKey)).toEqual(false);
		expect(verify(message, tampered, publicKey)).toEqual(false);
	});
});
