// Tests src/grimoire/post-quantum/Lamport/lamport.ts against the pinned
// known-answer vectors in test/vectors/lamport-vectors.json (generated by
// scripts/gen-lamport-vectors.ts), and with a fresh, live keygen/sign/
// verify round trip plus the reuse-forgery case study — the actual "this
// scheme really breaks on reuse" proof, not just asserted, same spirit as
// YoloRSA.test.ts's live crack/forge round trip.
import {expect} from 'earl';
import {describe, it} from 'node:test';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {keygen, hashToDigest, sign, verify, forgeFromTwoSignatures} from '../../src/grimoire/post-quantum/Lamport/lamport.js';

function fromHex(h: string): Uint8Array {
	return new Uint8Array(Buffer.from(h.slice(2), 'hex'));
}

interface Vectors {
	nBits: number;
	publicKey: {zero: string[]; one: string[]};
	signVectors: {message: string; digest: string; signature: string[]}[];
	invalidVector: {digest: string; signature: string[]};
	forgeryVector: {
		baseDigest: string;
		baseSignature: string[];
		complementDigest: string;
		complementSignature: string[];
		targetDigest: string;
		forgedSignature: string[];
	};
}

const vectorsJson: Vectors = JSON.parse(
	readFileSync(fileURLToPath(new URL('../vectors/lamport-vectors.json', import.meta.url)), 'utf8'),
);

const publicKey = {
	zero: vectorsJson.publicKey.zero.map(fromHex),
	one: vectorsJson.publicKey.one.map(fromHex),
};

describe('Lamport (grimoire, post-quantum) — pinned known-answer vectors', function () {
	for (const [i, v] of vectorsJson.signVectors.entries()) {
		it(`accepts sign vector ${i} ("${v.message}")`, function () {
			const digest = fromHex(v.digest);
			const signature = v.signature.map(fromHex);
			expect(verify(digest, signature, publicKey)).toEqual(true);
		});
	}

	it('rejects the pinned invalid (tampered-digest) vector', function () {
		const {digest, signature} = vectorsJson.invalidVector;
		expect(verify(fromHex(digest), signature.map(fromHex), publicKey)).toEqual(false);
	});

	it('the pinned forgery vector verifies — a signature over a digest that was never signed', function () {
		const {targetDigest, forgedSignature} = vectorsJson.forgeryVector;
		expect(verify(fromHex(targetDigest), forgedSignature.map(fromHex), publicKey)).toEqual(true);
	});
});

describe('Lamport — live round trip and forgery, not just pinned vectors', function () {
	it('signs and verifies freshly, at a fresh keypair', function () {
		const kp = keygen();
		const digest = hashToDigest(new TextEncoder().encode('a fresh message, not in any pinned vector'));
		const signature = sign(digest, kp.secretKey);
		expect(verify(digest, signature, kp.publicKey)).toEqual(true);

		// Tampering the digest, or reusing another digest's signature,
		// must both fail.
		const otherDigest = hashToDigest(new TextEncoder().encode('a different message'));
		expect(verify(otherDigest, signature, kp.publicKey)).toEqual(false);
	});

	it('the one-time-use break is real: two live signatures over complementary digests forge a signature the owner never made', function () {
		const kp = keygen();
		const base = hashToDigest(new TextEncoder().encode('the legitimate spend, fresh keypair'));
		const complement = Uint8Array.from(base.map((b) => b ^ 0xff));
		const baseSig = sign(base, kp.secretKey);
		const complementSig = sign(complement, kp.secretKey);
		expect(verify(base, baseSig, kp.publicKey)).toEqual(true);
		expect(verify(complement, complementSig, kp.publicKey)).toEqual(true);

		const target = hashToDigest(new TextEncoder().encode('a forged transaction, fresh keypair'));
		const forged = forgeFromTwoSignatures(base, baseSig, complement, complementSig, target);
		expect(verify(target, forged, kp.publicKey)).toEqual(true);
	});

	it('forgeFromTwoSignatures throws rather than silently failing when a bit position has no coverage', function () {
		const kp = keygen();
		const d1 = hashToDigest(new TextEncoder().encode('message one'));
		const d2 = hashToDigest(new TextEncoder().encode('message two')); // not the bitwise complement — likely incomplete coverage
		const sig1 = sign(d1, kp.secretKey);
		const sig2 = sign(d2, kp.secretKey);
		const target = hashToDigest(new TextEncoder().encode('an arbitrary third message'));

		// With non-complementary digests, coverage isn't guaranteed — this
		// should either succeed (if bits happen to cover) or throw, never
		// silently produce a signature that fails to verify.
		try {
			const forged = forgeFromTwoSignatures(d1, sig1, d2, sig2, target);
			expect(verify(target, forged, kp.publicKey)).toEqual(true);
		} catch (err) {
			expect(err instanceof Error).toEqual(true);
			expect((err as Error).message.includes('never revealed')).toEqual(true);
		}
	});
});
