// Tests the 2-word (up to 512-bit) LightningRSA wire encoding/decoding and
// verification math against the pinned known-answer vectors in
// test/vectors/lightning-rsa-vectors.json (generated by
// scripts/gen-lightning-rsa-vectors.ts), and with a fresh live sign/verify
// round trip at a size distinct from every pinned tier. Same reasoning as
// YoloRSA.test.ts for why there's no EVM/Hardhat deployment here: the
// deployable account (src/grimoire/LightningRSA/LightningRSAAccount.yul)
// needs EIP-8141 opcodes only the live ethrex testnet has.
import {expect} from 'earl';
import {describe, it} from 'node:test';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {generateKeypair, sign, verify} from './utils/yoloRSA.js';
import {splitWords, joinWords, wordsNeeded} from './utils/bigWord.js';

interface TierVectors {
	name: string;
	bits: number;
	e: string;
	nHigh: string;
	nLow: string;
	signVectors: {msgHash: string; sHigh: string; sLow: string}[];
	invalidVector: {msgHash: string; sHigh: string; sLow: string};
}

const vectorsJson: {tiers: TierVectors[]} = JSON.parse(
	readFileSync(
		fileURLToPath(new URL('../vectors/lightning-rsa-vectors.json', import.meta.url)),
		'utf8',
	),
);

describe('LightningRSA (grimoire) — bigWord split/join round-trips', function () {
	it('splits and rejoins a 2-word value losslessly', function () {
		const value = (1n << 400n) + 12345n;
		const words = splitWords(value, 2);
		expect(words.length).toEqual(2);
		expect(joinWords(words)).toEqual(value);
	});

	it('rejects a value that does not fit in the requested word count', function () {
		expect(() => splitWords(1n << 512n, 2)).toThrow();
	});

	it('reports the word count a value actually needs', function () {
		expect(wordsNeeded(0n)).toEqual(1);
		expect(wordsNeeded((1n << 256n) - 1n)).toEqual(1);
		expect(wordsNeeded(1n << 256n)).toEqual(2);
	});
});

describe('LightningRSA (grimoire) — pinned known-answer vectors', function () {
	for (const tier of vectorsJson.tiers) {
		describe(`tier: ${tier.name} (${tier.bits}-bit n)`, function () {
			const n = joinWords([BigInt(tier.nHigh), BigInt(tier.nLow)]);
			const e = BigInt(tier.e);

			it('n genuinely exceeds 2^256 (the account-level precondition)', function () {
				expect(n > (1n << 256n) - 1n).toEqual(true);
			});

			for (const [i, v] of tier.signVectors.entries()) {
				it(`accepts sign vector ${i}`, function () {
					const signature = joinWords([BigInt(v.sHigh), BigInt(v.sLow)]);
					expect(verify(BigInt(v.msgHash), signature, e, n)).toEqual(true);
				});
			}

			it('rejects the pinned invalid vector', function () {
				const badSignature = joinWords([
					BigInt(tier.invalidVector.sHigh),
					BigInt(tier.invalidVector.sLow),
				]);
				expect(verify(BigInt(tier.invalidVector.msgHash), badSignature, e, n)).toEqual(false);
			});
		});
	}
});

describe('LightningRSA — live sign/verify round trip, not just pinned vectors', function () {
	it('signs, splits into words, rejoins, and verifies at a size distinct from every pinned tier', function () {
		// 320 bits: > 2^256 (so the message-representative simplification
		// holds, same as every real tier) but matches none of
		// gen-lightning-rsa-vectors.ts's tiers.
		const kp = generateKeypair(320);
		expect(kp.n > (1n << 256n) - 1n).toEqual(true);

		const msgHash = 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef01234567n;
		const signature = sign(msgHash, kp.d, kp.n);

		const words = splitWords(signature, 2);
		const roundTripped = joinWords(words);
		expect(roundTripped).toEqual(signature);
		expect(verify(msgHash, roundTripped, kp.e, kp.n)).toEqual(true);

		// Tampering either word must break verification.
		const [sHigh, sLow] = words;
		expect(verify(msgHash, joinWords([sHigh ^ 1n, sLow]), kp.e, kp.n)).toEqual(false);
		expect(verify(msgHash, joinWords([sHigh, sLow ^ 1n]), kp.e, kp.n)).toEqual(false);
	});
});
