// Tests src/grimoire/post-quantum/ClassicMcEliece/mcEliece.ts against the
// pinned known-answer vectors in test/vectors/mceliece-vectors.json
// (generated by scripts/gen-mceliece-vectors.ts, which exhaustively
// round-trips all 2^k=128 possible messages with a fresh keypair each
// time before pinning anything — the actual proof, same discipline as
// ToyCurveECDH's brute-force group-order verification), plus a fresh live
// round trip and an exhaustive sweep run directly in this test.
import {expect} from 'earl';
import {describe, it} from 'node:test';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {keygen, encrypt, decrypt, PARAMS} from '../../src/grimoire/post-quantum/ClassicMcEliece/mcEliece.js';

interface Vectors {
	scheme: string;
	goppaPolynomial: number[];
	publicKey: (0 | 1)[][];
	secretKey: {Sinv: (0 | 1)[][]; permInv: number[]};
	vectors: {message: (0 | 1)[]; cipherText: (0 | 1)[]}[];
}

const vectorsJson: Vectors = JSON.parse(
	readFileSync(fileURLToPath(new URL('../vectors/mceliece-vectors.json', import.meta.url)), 'utf8'),
);

describe('McEliece (grimoire, post-quantum) — pinned known-answer vectors', function () {
	it('reports the expected toy parameters', function () {
		expect(PARAMS.n).toEqual(15);
		expect(PARAMS.k).toEqual(7);
		expect(PARAMS.t).toEqual(2);
	});

	for (const [i, v] of vectorsJson.vectors.entries()) {
		it(`decrypts pinned vector ${i} (message ${v.message.join('')}) back to the original message`, function () {
			const recovered = decrypt(v.cipherText, vectorsJson.secretKey);
			expect(recovered).toEqual(v.message);
		});
	}
});

describe('McEliece — live round trip and exhaustive sweep, not just pinned vectors', function () {
	it('encrypts and decrypts freshly, at a fresh keypair', function () {
		const kp = keygen();
		const message: (0 | 1)[] = [1, 0, 1, 1, 0, 0, 1];
		const cipherText = encrypt(message, kp.publicKey);
		const recovered = decrypt(cipherText, kp.secretKey);
		expect(recovered).toEqual(message);
	});

	it('every one of the 2^k possible messages round-trips correctly with a fresh keypair each time', function () {
		const total = 1 << PARAMS.k;
		for (let m = 0; m < total; m++) {
			const message = Array.from({length: PARAMS.k}, (_, i) => ((m >> i) & 1) as 0 | 1);
			const kp = keygen();
			const cipherText = encrypt(message, kp.publicKey);
			const recovered = decrypt(cipherText, kp.secretKey);
			expect(recovered).toEqual(message);
		}
	});

	it('a bounded-distance decoder has no guarantee beyond its correction radius: over-capacity corruption throws most of the time, but not always', function () {
		// Only 121 of the 256 possible 8-bit syndromes correspond to a
		// weight<=2 error; the other 135 are simply not in the table. An
		// over-capacity corruption's syndrome lands in the table (silently
		// "succeeding" with a wrong answer) with roughly (256-121)/256 ~=
		// 53% probability of throwing, NOT 100% — same as any real
		// bounded-distance decoder (Patterson's algorithm included): there
		// is no guarantee once you exceed t errors, only within it. Flipping
		// 6 fixed positions (0-5) on top of encrypt()'s own weight-2 error
		// guarantees an actual error weight in [4, 8] (symmetric-difference
		// argument) — always over capacity — but "over capacity" means "no
		// guarantee", not "always throws". Assert the statistically
		// meaningful thing instead: across enough trials, both outcomes
		// actually occur — proving decrypt() neither over-claims ("always
		// succeeds") nor under-claims ("always throws") beyond the
		// correction radius. (Whether a non-throwing result happens to
		// coincidentally match the original message isn't asserted here —
		// with a 1/128 message space, rare coincidental matches are
		// possible and would make that specific assertion flaky, not
		// meaningfully informative.)
		let sawThrow = false;
		let sawSilentDecode = false;
		for (let trial = 0; trial < 30; trial++) {
			const kp = keygen();
			const message: (0 | 1)[] = [0, 1, 0, 1, 0, 1, 0];
			const cipherText = encrypt(message, kp.publicKey);
			const overCorrupted = cipherText.map((b, i) => (i < 6 ? ((b ^ 1) as 0 | 1) : b));
			try {
				decrypt(overCorrupted, kp.secretKey);
				sawSilentDecode = true;
			} catch {
				sawThrow = true;
			}
		}
		expect(sawThrow).toEqual(true);
		expect(sawSilentDecode).toEqual(true);
	});
});
