// Tests src/grimoire/post-quantum/MlKem/mlKem.ts (a from-scratch ML-KEM-512
// / FIPS 203 implementation) against the pinned known-answer vectors in
// test/vectors/ml-kem-vectors.json (generated by
// scripts/gen-ml-kem-vectors.ts, byte-exact-checked against
// @noble/post-quantum there), and with a fresh, live keygen/encaps/decaps
// round trip cross-checked against @noble/post-quantum directly in this
// test — the actual "this really is FIPS 203, not just internally
// consistent" proof, same spirit as ToyCurveECDH.test.ts's live exchange.
import {expect} from 'earl';
import {describe, it} from 'node:test';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {randomBytes} from 'node:crypto';
import {keygen, encapsulate, decapsulate} from '../../src/grimoire/post-quantum/MlKem/mlKem.js';
import {ml_kem512} from '@noble/post-quantum/ml-kem.js';

function fromHex(h: string): Uint8Array {
	return new Uint8Array(Buffer.from(h.slice(2), 'hex'));
}

interface Vectors {
	scheme: string;
	sizes: {encapsulationKey: number; decapsulationKey: number; cipherText: number; sharedSecret: number};
	keyVectors: {seed: string; msgRand: string; ek: string; dk: string; cipherText: string; sharedSecret: string}[];
	implicitRejectionVector: {seed: string; msgRand: string; ek: string; dk: string; tamperedCipherText: string; fallbackSharedSecret: string};
}

const vectorsJson: Vectors = JSON.parse(
	readFileSync(fileURLToPath(new URL('../vectors/ml-kem-vectors.json', import.meta.url)), 'utf8'),
);

describe('MlKem (grimoire, post-quantum) — pinned known-answer vectors', function () {
	for (const [i, v] of vectorsJson.keyVectors.entries()) {
		describe(`vector ${i}`, function () {
			const seed = fromHex(v.seed);
			const msgRand = fromHex(v.msgRand);

			it('keygen matches the pinned encapsulation/decapsulation keys', function () {
				const {ek, dk} = keygen(seed);
				expect(ek).toEqual(fromHex(v.ek));
				expect(dk).toEqual(fromHex(v.dk));
			});

			it('encapsulate matches the pinned ciphertext and shared secret', function () {
				const {ek} = keygen(seed);
				const {cipherText, sharedSecret} = encapsulate(ek, msgRand);
				expect(cipherText).toEqual(fromHex(v.cipherText));
				expect(sharedSecret).toEqual(fromHex(v.sharedSecret));
			});

			it('decapsulate recovers the pinned shared secret from the pinned ciphertext', function () {
				const {dk} = keygen(seed);
				const recovered = decapsulate(fromHex(v.cipherText), dk);
				expect(recovered).toEqual(fromHex(v.sharedSecret));
			});
		});
	}

	it('implicit rejection: a tampered ciphertext falls back to the pinned pseudorandom value, not the real shared secret', function () {
		const v = vectorsJson.implicitRejectionVector;
		const recovered = decapsulate(fromHex(v.tamperedCipherText), fromHex(v.dk));
		expect(recovered).toEqual(fromHex(v.fallbackSharedSecret));
		expect(recovered.length).toEqual(32);
	});
});

describe('MlKem — live round trip, cross-checked against @noble/post-quantum directly', function () {
	it('keygen/encapsulate/decapsulate are byte-exact against a real FIPS 203 implementation, at a fresh seed', function () {
		const seed = new Uint8Array(randomBytes(64));

		const mine = keygen(seed);
		const theirs = ml_kem512.keygen(seed);
		expect(mine.ek).toEqual(theirs.publicKey);
		expect(mine.dk).toEqual(theirs.secretKey);

		const msgRand = new Uint8Array(randomBytes(32));
		const mineEnc = encapsulate(mine.ek, msgRand);
		const theirsEnc = ml_kem512.encapsulate(theirs.publicKey, msgRand);
		expect(mineEnc.cipherText).toEqual(theirsEnc.cipherText);
		expect(mineEnc.sharedSecret).toEqual(theirsEnc.sharedSecret);

		// Cross-interop, both directions — proves wire-format compatibility,
		// not just "both independently round-trip".
		expect(decapsulate(theirsEnc.cipherText, mine.dk)).toEqual(theirsEnc.sharedSecret);
		// Casts below: TS's split between Uint8Array<ArrayBufferLike> and
		// Uint8Array<ArrayBuffer> — a typings-only distinction (also
		// present, inconsistently, inside @noble/post-quantum's own .d.ts)
		// unrelated to the actual bytes this test checks.
		const theirDecapWithMyCipherText = ml_kem512.decapsulate(
			mineEnc.cipherText as Uint8Array<ArrayBuffer>,
			theirs.secretKey as Uint8Array<ArrayBuffer>,
		);
		expect(theirDecapWithMyCipherText as Uint8Array).toEqual(mineEnc.sharedSecret as Uint8Array);
	});

	it('rejects a tampered ciphertext (fresh, live) the same way a real implementation does', function () {
		const seed = new Uint8Array(randomBytes(64));
		const {ek, dk} = keygen(seed);
		const msgRand = new Uint8Array(randomBytes(32));
		const {sharedSecret, cipherText} = encapsulate(ek, msgRand);

		const tampered = Uint8Array.from(cipherText);
		tampered[0]! ^= 1;

		const mine = decapsulate(tampered, dk);
		const theirs = ml_kem512.decapsulate(tampered, dk);
		expect(mine).not.toEqual(sharedSecret);
		expect(mine).toEqual(theirs);
	});
});
