// Tests the pure-JS/bigint NTRUSign reference (test/js/utils/ntruSign.ts)
// against the pinned known-answer vectors in test/vectors/ntrusign-vectors.json
// (generated by scripts/gen-ntrusign-vectors.ts, which also re-confirms the
// legit-vs-cross-message closeness gap the scheme depends on — see that
// script and ntruSign.ts's header for why N=18 works where N=11 didn't),
// plus a fresh, live keygen -> sign -> verify round trip and a fresh
// cross-message rejection check — the actual proof, not just pinned
// vectors. No EVM/Hardhat network involved here: covered separately once
// the Yul account/harness land (see the plan).
import {expect} from 'earl';
import {describe, it} from 'node:test';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {keccak_256} from '@noble/hashes/sha3.js';
import {keygen, sign, verify, N, Q, CLOSENESS_BOUND, type Poly} from './utils/ntruSign.js';

interface Vectors {
	params: {N: number; Q: string; closenessBound: string};
	key: {f: string[]; g: string[]; F: string[]; G: string[]; h: string[]};
	signVectors: {message: string; msgHash: string; signature: string[]; closeness: string}[];
	closenessGapSweep: {numKeys: number; numMessagesPerKey: number; legitMax: string; crossMin: string};
}

const vectorsJson: Vectors = JSON.parse(
	readFileSync(fileURLToPath(new URL('../vectors/ntrusign-vectors.json', import.meta.url)), 'utf8'),
);

function toPoly(strs: string[]): Poly {
	return strs.map((s) => BigInt(s));
}
function toBytes(hex: string): Uint8Array {
	return new Uint8Array(Buffer.from(hex.slice(2), 'hex'));
}

describe('NTRUSign (tools) — parameters and pinned vectors', function () {
	it('reports the locked toy parameters', function () {
		expect(N).toEqual(18);
		expect(Q).toEqual(128n);
		expect(vectorsJson.params.N).toEqual(N);
		expect(vectorsJson.params.Q).toEqual(Q.toString());
	});

	it('the pinned closeness-gap sweep found a real gap, and CLOSENESS_BOUND sits inside it', function () {
		const legitMax = BigInt(vectorsJson.closenessGapSweep.legitMax);
		const crossMin = BigInt(vectorsJson.closenessGapSweep.crossMin);
		expect(legitMax < crossMin).toEqual(true);
		expect(legitMax < CLOSENESS_BOUND).toEqual(true);
		expect(crossMin > CLOSENESS_BOUND).toEqual(true);
	});

	for (const v of vectorsJson.signVectors) {
		it(`pinned signature for "${v.message}" verifies against its own message`, function () {
			const key = {f: toPoly(vectorsJson.key.f), g: toPoly(vectorsJson.key.g), F: toPoly(vectorsJson.key.F), G: toPoly(vectorsJson.key.G), h: toPoly(vectorsJson.key.h)};
			const msgHash = toBytes(v.msgHash);
			const s = toPoly(v.signature);
			expect(verify(msgHash, s, key.h)).toEqual(true);
		});
	}

	it('the pinned f*G-g*F=q key equation holds exactly for the pinned key', function () {
		const {f, g, F, G} = vectorsJson.key;
		const N_ = N;
		const fP = toPoly(f), gP = toPoly(g), FP = toPoly(F), GP = toPoly(G);
		const polyMul = (a: Poly, b: Poly): Poly => {
			const out = new Array<bigint>(N_).fill(0n);
			for (let i = 0; i < N_; i++) for (let j = 0; j < N_; j++) out[(i + j) % N_]! += a[i]! * b[j]!;
			return out;
		};
		const lhs = polyMul(fP, GP).map((v, i) => v - polyMul(gP, FP)[i]!);
		expect(lhs[0]).toEqual(Q);
		for (let i = 1; i < N_; i++) expect(lhs[i]).toEqual(0n);
	});
});

describe('NTRUSign — live keygen/sign/verify round trip, not just pinned vectors', function () {
	it('generates a fresh keypair, signs, and verifies "hello world"', function () {
		const key = keygen();
		const msgHash = keccak_256(new TextEncoder().encode('hello world'));
		const s = sign(msgHash, key);
		expect(verify(msgHash, s, key.h)).toEqual(true);
	});

	it('rejects a signature checked against an unrelated message — the actual security property', function () {
		const key = keygen();
		const msgA = keccak_256(new TextEncoder().encode('hello world'));
		const msgB = keccak_256(new TextEncoder().encode('goodbye world'));
		const s = sign(msgA, key);
		expect(verify(msgA, s, key.h)).toEqual(true);
		expect(verify(msgB, s, key.h)).toEqual(false);
	});

	it('rejects a signature from a DIFFERENT keypair, even for the same message', function () {
		const keyA = keygen();
		const keyB = keygen();
		const msgHash = keccak_256(new TextEncoder().encode('hello world'));
		const s = sign(msgHash, keyA);
		expect(verify(msgHash, s, keyB.h)).toEqual(false);
	});

	it('20 fresh keypairs all sign and verify correctly, at least once each', function () {
		for (let i = 0; i < 20; i++) {
			const key = keygen();
			const msgHash = keccak_256(new TextEncoder().encode(`trial ${i}`));
			const s = sign(msgHash, key);
			expect(verify(msgHash, s, key.h)).toEqual(true);
		}
	});
});
