// Deploys src/grimoire/StarkPedersen/StarkPedersen.yul to Hardhat's local
// simulated network and checks it three ways: against the known-answer
// vectors in test/vectors/stark-pedersen-vectors.json (generated by
// scripts/gen-stark-pedersen-vectors.ts from the independent JS/bigint
// mirror in test/js/utils/starkPedersen.ts), directly against
// `@scure/starknet`'s own `pedersen()` for values not in the pinned set —
// the actual ground-truth proof, same spirit as MlKem.test.ts's noble
// interop check — and against the two correctness guards the contract is
// supposed to enforce (out-of-range inputs, and the "same x-coordinate"
// collision guard).
import {expect} from 'earl';
import {describe, it, before} from 'node:test';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import solc from 'solc';
import {network} from 'hardhat';
import {getContract, type Hex} from 'viem';
import {pedersen as scurePedersen} from '@scure/starknet';
import {P} from './utils/starkPedersen.js';

interface WirePoint {
	x: string;
	y: string;
}
interface StarkPedersenVectors {
	curve: {p: string; a: string; b: string};
	points: {shift: WirePoint; p0: WirePoint; p1: WirePoint; p2: WirePoint; p3: WirePoint};
	chordAdd: {p1: WirePoint; p2: WirePoint; expected: WirePoint}[];
	tangentDouble: {p: WirePoint; expected: WirePoint}[];
	pedersen: {x: string; y: string; expected: string}[];
}

const vectorsJson: StarkPedersenVectors = JSON.parse(
	readFileSync(
		fileURLToPath(new URL('../vectors/stark-pedersen-vectors.json', import.meta.url)),
		'utf8',
	),
);

const abi = [
	{
		type: 'function',
		name: 'pedersen',
		stateMutability: 'pure',
		inputs: [{type: 'uint256'}, {type: 'uint256'}],
		outputs: [{type: 'uint256'}],
	},
	{
		type: 'function',
		name: 'jia_add',
		stateMutability: 'pure',
		inputs: [{type: 'uint256'}, {type: 'uint256'}, {type: 'uint256'}, {type: 'uint256'}],
		outputs: [{type: 'uint256'}, {type: 'uint256'}],
	},
	{
		type: 'function',
		name: 'xian_chord',
		stateMutability: 'pure',
		inputs: [{type: 'uint256'}, {type: 'uint256'}, {type: 'uint256'}, {type: 'uint256'}],
		outputs: [{type: 'uint256'}, {type: 'uint256'}],
	},
	{
		type: 'function',
		name: 'qie_tangent',
		stateMutability: 'pure',
		inputs: [{type: 'uint256'}, {type: 'uint256'}],
		outputs: [{type: 'uint256'}, {type: 'uint256'}],
	},
] as const;

function compileYul(sourcePath: string): Hex {
	const src = readFileSync(sourcePath, 'utf8');
	const input = {
		language: 'Yul',
		sources: {[sourcePath]: {content: src}},
		settings: {outputSelection: {'*': {'*': ['evm.bytecode.object']}}},
	};
	const output = JSON.parse(solc.compile(JSON.stringify(input)));
	const errors = (output.errors ?? []).filter(
		(e: {severity: string}) => e.severity === 'error',
	);
	if (errors.length > 0) {
		throw new Error(
			'Yul compilation failed:\n' +
				errors
					.map((e: {formattedMessage: string}) => e.formattedMessage)
					.join('\n'),
		);
	}
	const contractName = Object.keys(output.contracts[sourcePath])[0]!;
	return `0x${output.contracts[sourcePath][contractName].evm.bytecode.object}` as Hex;
}

const {viem} = await network.create();

describe('StarkPedersen (grimoire)', function () {
	let contract: Awaited<ReturnType<typeof deploy>>;

	async function deploy() {
		const [wallet] = await viem.getWalletClients();
		const publicClient = await viem.getPublicClient();
		const yulPath = fileURLToPath(
			new URL(
				'../../src/grimoire/StarkPedersen/StarkPedersen.yul',
				import.meta.url,
			),
		);
		const initBytecode = compileYul(yulPath);
		const hash = await wallet!.sendTransaction({data: initBytecode});
		const receipt = await publicClient.waitForTransactionReceipt({hash});
		return getContract({
			address: receipt.contractAddress!,
			abi,
			client: {public: publicClient, wallet: wallet!},
		});
	}

	before(async function () {
		contract = await deploy();
	});

	it('reports the expected curve modulus', function () {
		expect(vectorsJson.curve.p).toEqual(P.toString());
	});

	it('xian_chord matches known-answer chord (distinct-point addition) vectors', async function () {
		for (const v of vectorsJson.chordAdd) {
			const [x3, y3] = await contract.read.xian_chord([
				BigInt(v.p1.x),
				BigInt(v.p1.y),
				BigInt(v.p2.x),
				BigInt(v.p2.y),
			]);
			expect(x3).toEqual(BigInt(v.expected.x));
			expect(y3).toEqual(BigInt(v.expected.y));
		}
	});

	it('jia_add matches the same chord vectors (the guarded dispatcher, not just the raw geometry)', async function () {
		for (const v of vectorsJson.chordAdd) {
			const [x3, y3] = await contract.read.jia_add([
				BigInt(v.p1.x),
				BigInt(v.p1.y),
				BigInt(v.p2.x),
				BigInt(v.p2.y),
			]);
			expect(x3).toEqual(BigInt(v.expected.x));
			expect(y3).toEqual(BigInt(v.expected.y));
		}
	});

	it('qie_tangent matches known-answer doubling vectors', async function () {
		for (const v of vectorsJson.tangentDouble) {
			const [x3, y3] = await contract.read.qie_tangent([BigInt(v.p.x), BigInt(v.p.y)]);
			expect(x3).toEqual(BigInt(v.expected.x));
			expect(y3).toEqual(BigInt(v.expected.y));
		}
	});

	it('pedersen matches every pinned known-answer vector', async function () {
		for (const v of vectorsJson.pedersen) {
			const h = await contract.read.pedersen([BigInt(v.x), BigInt(v.y)]);
			expect(h).toEqual(BigInt(v.expected));
		}
	});

	it('pedersen matches @scure/starknet directly, for fresh values not in the pinned set — the actual proof', async function () {
		const freshCases: [bigint, bigint][] = [
			[42n, 1337n],
			[999999999999999999999999999999999999999999999999999999999999999999999999n, 3n],
			[P - 2n, 5n],
		];
		for (const [x, y] of freshCases) {
			const onChain = await contract.read.pedersen([x, y]);
			const groundTruth = BigInt(scurePedersen(x, y));
			expect(onChain).toEqual(groundTruth);
		}
	});

	it('rejects (reverts) an input that is not a valid field element (x >= P)', async function () {
		await expect(contract.read.pedersen([P, 1n])).toBeRejected();
		await expect(contract.read.pedersen([1n, P])).toBeRejected();
	});

	it('rejects (reverts) adding a point to itself via jia_add — the collision guard, not a silent double', async function () {
		const p = vectorsJson.points.p0;
		await expect(
			contract.read.jia_add([BigInt(p.x), BigInt(p.y), BigInt(p.x), BigInt(p.y)]),
		).toBeRejected();
	});

	it('measures the real gas cost of one pedersen(x, y) call, honestly, rather than guessing', async function () {
		const publicClient = await viem.getPublicClient();
		const [wallet] = await viem.getWalletClients();
		const gas = await publicClient.estimateContractGas({
			address: contract.address,
			abi,
			functionName: 'pedersen',
			args: [123456789n, 987654321n],
			account: wallet!.account,
		});
		// Not a tight assertion on the exact figure (that would make this
		// test brittle against unrelated solc/opcode-pricing changes) — just
		// a sanity bound confirming it stays in "expensive but practical on
		// a real block," not "the gas count regressed to something absurd."
		console.log(`  measured gas for pedersen(x, y): ${gas.toString()}`);
		expect(gas > 100_000n).toEqual(true);
		expect(gas < 10_000_000n).toEqual(true);
	});
});
