// Tests the pure-JS/bigint YoloRSA mirror (test/js/utils/yoloRSA.ts) two
// ways: against the pinned known-answer vectors in
// test/vectors/yolo-rsa-vectors.json (generated by
// scripts/gen-yolo-rsa-vectors.ts — the same numbers are also hardcoded
// into test/solidity/YoloRSA/YoloRSA.t.sol, proving the JS and Solidity
// implementations agree), and with a fresh, live sign -> verify -> crack ->
// forge round trip — the actual "this is really breakable" proof, not just
// pinned vectors. No EVM/Hardhat network involved: the deployable account
// (src/grimoire/YoloRSA/YoloRSAAccount.yul) needs EIP-8141 opcodes that
// only exist on the live ethrex testnet, so — same reasoning
// NostrFrameAccount.yul's lack of a .test.ts follows — it isn't
// Hardhat-testable locally; only the pure verification math is covered
// here and in YoloRSA.t.sol.
import {expect} from 'earl';
import {describe, it} from 'node:test';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {
	generateKeypair,
	sign,
	verify,
	factor,
	crackPrivateExponent,
} from './utils/yoloRSA.js';

interface TierVectors {
	name: string;
	bits: number;
	n: string;
	e: string;
	signVectors: {msgHash: string; signature: string; messageRepresentative: string}[];
	invalidVector: {msgHash: string; signature: string};
}

const vectorsJson: {tiers: TierVectors[]} = JSON.parse(
	readFileSync(
		fileURLToPath(new URL('../vectors/yolo-rsa-vectors.json', import.meta.url)),
		'utf8',
	),
);

describe('YoloRSA (grimoire) — pinned known-answer vectors', function () {
	for (const tier of vectorsJson.tiers) {
		describe(`tier: ${tier.name} (${tier.bits}-bit n)`, function () {
			const n = BigInt(tier.n);
			const e = BigInt(tier.e);

			for (const [i, v] of tier.signVectors.entries()) {
				it(`accepts sign vector ${i}`, function () {
					const ok = verify(BigInt(v.msgHash), BigInt(v.signature), e, n);
					expect(ok).toEqual(true);
				});
			}

			it('rejects the pinned invalid vector', function () {
				const ok = verify(
					BigInt(tier.invalidVector.msgHash),
					BigInt(tier.invalidVector.signature),
					e,
					n,
				);
				expect(ok).toEqual(false);
			});
		});
	}
});

describe('YoloRSA — live sign/verify/crack round trip, not just pinned vectors', function () {
	it('signs and verifies freshly, at a size distinct from every pinned tier', function () {
		// 40 bits matches none of gen-yolo-rsa-vectors.ts's tiers — this
		// exercises generateKeypair/sign/verify end to end, independent of
		// anything pinned above.
		const kp = generateKeypair(40);
		const msgHash = 0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdn;

		const signature = sign(msgHash, kp.d, kp.n);
		expect(verify(msgHash, signature, kp.e, kp.n)).toEqual(true);

		// Tampering the signature by one must break verification.
		expect(verify(msgHash, (signature + 1n) % kp.n, kp.e, kp.n)).toEqual(false);
		// Signing a different message must produce a signature that fails
		// against the first message's representative.
		const otherHash = 0xdeadbeefn;
		const otherSignature = sign(otherHash, kp.d, kp.n);
		if (otherSignature !== signature) {
			expect(verify(msgHash, otherSignature, kp.e, kp.n)).toEqual(false);
		}
	});

	it('cracks a fresh keypair (factor n -> recover d) and forges a valid signature the "owner" never made', function () {
		// This is the actual point of a yolo wallet: an "attacker" who only
		// ever sees the public (e, n) — never d — can still recover d and
		// sign on the account's behalf, purely from n being small.
		const kp = generateKeypair(40);
		const attackerMsgHash = 0x0ddba11deadbeef0badf00ddeadbeef0badf00ddeadbeef0badf00dn;

		const {p, q} = factor(kp.n);
		expect(p * q).toEqual(kp.n);
		expect([p, q].sort().toString()).toEqual([kp.p, kp.q].sort().toString());

		const recoveredD = crackPrivateExponent(p, q, kp.e);
		expect(recoveredD).toEqual(kp.d);

		// The attacker, holding only the recovered d (never the real one,
		// though they happen to match here), forges a signature over a
		// message the real owner never signed.
		const forgedSignature = sign(attackerMsgHash, recoveredD, kp.n);
		expect(verify(attackerMsgHash, forgedSignature, kp.e, kp.n)).toEqual(true);
	});
});
