// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Test} from "forge-std/Test.sol";
import {BIP340} from "src/BIP340/BIP340.sol";

/// @notice Known-answer + negative tests for the ecrecover-trick reduction.
/// The three "real" vectors below were generated by a noble-curves BIP-340
/// implementation via scripts/gen-vectors.ts, and the reduction was
/// cross-checked numerically in that script before ever being implemented
/// here (design doc §5.1 / §7) — see test/vectors/nostr-test-vectors.json
/// for the source of truth.
contract BIP340Test is Test {
    struct Vector {
        bytes32 px;
        address pAddress;
        bytes32 message;
        bytes32 rx;
        bytes32 s;
    }

    Vector internal v0 =
        Vector({
            px: 0x1b84c5567b126440995d3ed5aaba0565d71e1834604819ff9c17f5e9d5dd078f,
            pAddress: address(0x963f1B893656c4a739AE1Deb15f621B704c54022),
            message: 0xb2ab66db9a3ce11dd83dba85d66203fde36bb4715927ae4473098e422576ed22,
            rx: 0x4ab905e4c5b1737435feabd6d66f61c845747814adc58309baba7e17a0d9e027,
            s: 0x1c1591b30c75fb5f1de327fdfb6104e17473dd11046114dbd077ab3bc61d696e
        });

    Vector internal v1 =
        Vector({
            px: 0x016c0067e606010592df0dad684354c87cbd2c448c389a52723a299eeb64f3ef,
            pAddress: address(0xB3a49e713FadaF797DfD86FE9bDeA3C8e1dF7B57),
            message: 0x55c632b9d0111bf23aa8427ad3d3fb8c90336000a994e1c1b870d5bb871d287c,
            rx: 0x393e1ca49aafd9ad95ebbb7d73ba43a6bbf3dc7b0555182eae97cada82568e5e,
            s: 0x1e864110cba029c1b0ad2321f34a204f34a09943cab05acc26dc6544ed56660d
        });

    Vector internal v2 =
        Vector({
            px: 0x43cfe80403e5426fa501bd083a5cb4dcd36c455f0f11d012c58cda333d475071,
            pAddress: address(0xd2d7fAfD6Dded0ad00f4e7bd2C50edc65C1A9BF4),
            message: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,
            rx: 0x5d29ac7c41dc52e3f9921528663995f165b4fe87dbde1e85768f884677435816,
            s: 0x2ebea4ddb6b819bb1e32af6e2a16843a38a9eb9517baab17b4800681755c46c7
        });

    // Cross-reference vector (design doc §7 item 3): a *real* Nostr event,
    // signed by nostr-tools (not our own noble-curves calls) via
    // scripts/gen-nostr-tools-vector.ts — proves the "same key, two
    // protocols" claim against an actual Nostr signing library, not just
    // internal self-consistency. `message` is the NIP-01 event id
    // (sha256 of the serialized event) nostr-tools computed for:
    //   {"kind":1,"created_at":1735689600,"tags":[],
    //    "content":"nostr-frame: BIP-340 ecrecover-trick cross-check vector — see BIP340.t.sol"}
    // See test/vectors/nostr-test-vectors.json ("nostr-tools-real-event")
    // for the full signed event.
    Vector internal v3 =
        Vector({
            px: 0x4d4b6cd1361032ca9bd2aeb9d900aa4d45d9ead80ac9423374c451a7254d0766,
            pAddress: address(0x5050A4F4b3f9338C3472dcC01A87C76A144b3c9c),
            message: 0x0c96a2a033d62966daf3497e080424d69151c1126db8633b3efd8119bd860b88,
            rx: 0xd3a2bb06e6833e067d0c6ddc9ed4b1848ae0d2d209366e2ddb4a4248fa5d9a1e,
            s: 0x49fe5819e2e9e3e62bcb83a2da1487c49634130d62de42524b34da76a2220d75
        });

    function _verify(Vector memory v) internal view returns (bool) {
        return BIP340.verify(v.pAddress, v.px, v.rx, v.s, v.message);
    }

    // ==================== Known-answer tests (real signatures) ====================

    function test_vector0_valid() public view {
        assertTrue(_verify(v0));
    }

    function test_vector1_valid() public view {
        assertTrue(_verify(v1));
    }

    function test_vector2_valid() public view {
        assertTrue(_verify(v2));
    }

    function test_vector3_realNostrToolsEvent_valid() public view {
        assertTrue(_verify(v3));
    }

    // ==================== Negative tests ====================

    function test_wrongPAddress_rejected() public view {
        Vector memory v = v0;
        v.pAddress = address(uint160(v.pAddress) + 1);
        assertFalse(_verify(v));
    }

    function test_flippedBitInS_rejected() public view {
        Vector memory v = v0;
        v.s = v.s ^ bytes32(uint256(1));
        assertFalse(_verify(v));
    }

    function test_flippedBitInRx_rejected() public view {
        Vector memory v = v0;
        v.rx = v.rx ^ bytes32(uint256(1) << 200);
        assertFalse(_verify(v));
    }

    function test_flippedBitInPx_rejected() public view {
        Vector memory v = v0;
        v.px = v.px ^ bytes32(uint256(1));
        assertFalse(_verify(v));
    }

    function test_wrongMessage_rejected() public view {
        Vector memory v = v0;
        v.message = v1.message;
        assertFalse(_verify(v));
    }

    function test_crossedSignature_rejected() public view {
        // v0's (rx, s) against v1's (pAddress, px, message) — makes sure
        // nothing is silently ignored across the whole tuple.
        assertFalse(BIP340.verify(v1.pAddress, v1.px, v0.rx, v0.s, v1.message));
    }

    function test_pAddressZero_rejected() public view {
        Vector memory v = v0;
        v.pAddress = address(0);
        assertFalse(_verify(v));
    }

    function test_rxZero_rejected() public view {
        Vector memory v = v0;
        v.rx = bytes32(0);
        assertFalse(_verify(v));
    }

    function test_rxEqualsN_rejected() public view {
        // Non-canonical: Rx must be < N (see BIP340.sol's comment on why we
        // tighten to N rather than the literal spec's Rx < p).
        Vector memory v = v0;
        v.rx = bytes32(BIP340.N);
        assertFalse(_verify(v));
    }

    function test_sEqualsN_rejected() public view {
        // Non-canonical s (§5.4 malleability): s must be < N.
        Vector memory v = v0;
        v.s = bytes32(BIP340.N);
        assertFalse(_verify(v));
    }

    function test_sZero_isCanonicalButStillRejectedForRealSig() public view {
        // s == 0 is within the canonical [0, N) range per spec, but a real
        // signature's s is never 0, so this must still fail.
        Vector memory v = v0;
        v.s = bytes32(0);
        assertFalse(_verify(v));
    }
}
